version: '2.24.6'
services:
  learnboard-app:
    build: ./learnboard-app
    ports:
      - 3000:3000
    volumes:
      - ./learnboard-app:/app
    depends_on:
      - learnboard-server

  learnboard-server:
    build: ./learnboard-server
    ports:
      - 8000:8000
    volumes:
      - ./learnboard-server:/app