version: '2.25.6'
services:
  learnboard-server:
    build: ./learnboard-server
    ports:
      - 8000:8000
    volumes:
      - ./learnboard-server:/app
      - /etc/letsencrypt:/etc/letsencrypt:ro # Montar certificados SSL como solo lectura
